PREFIX leco: <https://w3id.org/leco/ontology#>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>

SELECT DISTINCT ?person ?office ?officeType ?date WHERE {
  ?holding a rico:PositionHoldingRelation ;
           rico:relationHasSource ?person ;
           rico:relationHasTarget ?office ;
           rico:relationHasDate ?date .
  ?office a leco:Office ; leco:hasOfficeType ?officeType .
}
ORDER BY ?person ?date
