PREFIX leco: <https://w3id.org/leco/ontology#>

SELECT DISTINCT ?decision ?argument ?rule WHERE {
  ?decision leco:hasLegalArgument ?argument .
  ?argument a leco:LegalArgument ;
            leco:argumentInvokesRule ?rule .
}
ORDER BY ?decision ?argument
